title: Kelly Savoy
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Software Engineering Manager
  
show_links: true;
linkedin_url: https://www.linkedin.com/in/kellyboland/
  
# slate specific stuff
github:
  repository_url: https://github.com/Nerdy3000
  is_user_page: true
  is_project_page: false

show_downloads: false
 
#remote_theme: samarsault/plainwhite-jekyll
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
